### ISSUE TITLE
Support for games with different titles.

### ISSUE THREAD

**Issue by CallumKerrEdwards** [game-curator/game-curator#20]
For example, @liamdawson said in issue #7 that they own the game Absolute Balderdash. BoardGameGeek [here](https://boardgamegeek.com/boardgame/1544/beyond-balderdash) suggests that the game is more commonly known as Beyond Balderdash. I am sure there are many more examples.

How should we handle this? Have an optional field on the games that specified additional names? Multiple entires on the selection screen that point to the same description? Some other solution?

**Comment by liamdawson** [comment]
Opened #22, which should cover this. The solution might lie with storing the BGG ID in game entries, and looking them up via BGG. Will have to give it some thought.

**Comment by CallumKerrEdwards** [comment]
Too old
