### ISSUE TITLE
Establish game data schema

### ISSUE THREAD

**Issue by liamdawson** [game-curator/game-curator#22]
* [x] Create a JSON schema to correspond to game entries
* [x] Formalize scales for fields such as rule and meta complexity

**Comment by CallumKerrEdwards** [comment]
Another area to formalise is the time. This should be easy, as BGG has a time field for most games. I am so far using:
<= 15 mins : Very short
<= 30 mins : Short
<= 1 hour : Medium
<= 2 hours: Long
> 2 hours : Very long

**Comment by liamdawson** [comment]
I'm thinking time and complexity scales will be a 1-5, roughly corresponding to the times you've mentioned there.

**Comment by CallumKerrEdwards** [comment]
Sounds good to me. Additionally for the data schema, I would suggest that the recommended players field be optional. Many of the games we currently have in have the same recommended number of players as possible number of players, therefore not providing any new information and just clutters up the byline.

**Comment by jgimbel** [comment]
I would suggest making the upper or lower limits optional. 

I can play as many people as I want in Werewolves, BANG, codenames, or dominion(when you have every expansion and the base cards again it adds up), . 
There are also games like Lord of the Rings LCG that will allow you to play on your own, but up to 4 people.

**Comment by liamdawson** [comment]
I've begun work with #24. I've made the "ideal" players count totally optional, and I'll consider leaving the maximum optional (in case of unlimited player games).

**Comment by liamdawson** [comment]
Left before I consider version 1 of the schema complete:

* [ ] Alternative names
* [ ] Uncapped max player count

Neither of these should be breaking changes.

**Comment by liamdawson** [comment]
Closing in favour of #28 due to large-scale changes.
