### ISSUE TITLE
Expansions inherit preferred players from base game without it necessarily being right.

### ISSUE THREAD

**Issue by CallumKerrEdwards** [game-curator/game-curator#27]
Eg. In Archipelago, one of the expansions is a solo expansion. I did not give it a recommended number of players, just a required. Now it inherits the 4-5 ideal from its parent, even though the ideal should either be the possible number or just 1.

**Comment by liamdawson** [comment]
Hmm, for the sake of brevity, I think I prefer the inheritance, as this is a much rarer case — I'd recommend setting the preferred players to [1, 1] on the expansion, unless you have another idea?

**Comment by CallumKerrEdwards** [comment]
I have added that change to the #26 pull request
