### ISSUE TITLE
Add all the games from my collection

### ISSUE THREAD

**Issue by liamdawson** [game-curator/game-curator#7]
Still yet personally to add entries for:

* [x] Pictionary
* [x] Halo Risk
* [ ] Absolute Balderdash
* [x] Concept
* [x] Munchkin
* [x] Taboo
* [x] Codenames
* [x] The Resistance

**Comment by jgimbel** [comment]
A quick look over at my collection has
- [ ] Boss Monster
- [ ] Cash & Guns
- [ ] Tsuro
- [ ] Codenames
- [ ] Flash Point
- [ ] Smash Up

**Comment by CallumKerrEdwards** [comment]
My collection - I will update this as I go.

- [x] 7 Wonders
- [ ] Archipelago
- [x] Carcassonne
- [ ] Cosmic Encounter
- [x] King of Tokyo
- [x] Pandemic 
- [x] Pictionary
- [x] Pictomania
- [ ] Tales of the Arabian Nights

**Comment by CallumKerrEdwards** [comment]
> Halo Risk
@liamdawson which game is this? BGG lists both Risk: Halo Legendary Edition and Risk: Halo Wars Collector's Edition.

**Comment by liamdawson** [comment]
@CallumKerrEdwards Halo Wars.

**Comment by liamdawson** [comment]
Will need to restart this work due to schema changes.
